name: imagej
channels:
  - conda-forge
  - defaults
dependencies:
  - imglyb
  - jpype1
  - jupyter_contrib_nbextensions
  - matplotlib-base
  - notebook
  - numpy
  - openjdk=8
  - scikit-image
  - scyjava
  - xarray
